
server:
  port: ${port:3008}

storage:
  location: upload-dir

# 定时任务 0/10 * *  * * ? 每隔十秒
cron:
  cronLocation: 0 36 11 * * ?


#mysql
spring:
  output:
    ansi:
      enabled: detect

  datasource:

      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: lzy
      password: 123456
      driverClassName:  com.mysql.jdbc.Driver
      tomcat:
            test-while-idle: true
            validation-query: SELECT 1
  jpa:
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
          naming:
            strategy: org.hibernate.cfg.ImprovedNamingStrategy
          ddl-auto: none
    show-sql: true
  http:
    multipart:
      maxFileSize: 100MB
      # Set the total request size for a multipart/form-data (default 10Mb)
      maxRequestSize: 30MB

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    defaultFetchSize: 100
    defaultStatementTimeout: 30

logging:
    level:
        root: info
        bsp:  debug
        com:
          spring:
            ibatis: DEBUG
        org:
            hibernate:
                SQL: DEBUG

# JWT
jwt:
  tokenHeader: Authorization
  secret: bestskip
  expiration: 31536000

