
#https://docs.spring.io/spring-boot/docs/1.5.18.RELEASE/reference/htmlsingle/#boot-documentation
server:
  port: ${port:3009}

storage:
  location: upload-dir

# 定时任务 0/10 * *  * * ? 每隔十秒
cron:
  cronLocation: 0 36 11 * * ?

# ADMIN (SpringApplicationAdminJmxAutoConfiguration)
#  spring.application.admin.enabled=false # Enable admin features for the application.
#  spring.application.admin.jmx-name=org.springframework.boot:type=Admin,name=SpringApplication # JMX name of the application admin MBean.
#
#mysql
spring:

  output:
    ansi:
      enabled: detect

  datasource:

      url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: lzy
      password: 123456
      driverClassName:  com.mysql.jdbc.Driver
      tomcat:
            test-while-idle: true
            validation-query: SELECT 1
  jpa:
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
          naming:
            strategy: org.hibernate.cfg.ImprovedNamingStrategy
          ddl-auto: update
    show-sql: true
  http:
    multipart:
      maxFileSize: 100MB
      # Set the total request size for a multipart/form-data (default 10Mb)
      maxRequestSize: 30MB

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    defaultFetchSize: 100
    defaultStatementTimeout: 30

logging:
    level:
        root: info
        bsp:  debug
        com:
          spring:
            ibatis: DEBUG
        org:
            hibernate:
                SQL: DEBUG
# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------
# SECURITY (SecurityProperties)


# JWT
jwt:
  tokenHeader: Authorization
  secret: longzhiyou
  expiration: 31536000

